import type { HouseFeatures } from './types';

export const INITIAL_FEATURES: HouseFeatures = {
  location: 'KLCC',
  propertyType: 'Condominium',
  rooms: 3,
  bathrooms: 2,
  carParks: 1,
  size: 1000,
  furnished: 'Fully Furnished'
};

export const LOCATIONS = [
  'Ampang',
  'Ampang Hilir',
  'Bandar Damai Perdana',
  'Bandar Menjalara',
  'Bandar Tasik Selatan',
  'Bangsar',
  'Bangsar South',
  'Batu Caves',
  'Brickfields',
  'Bukit Bintang',
  'Bukit Jalil',
  'Bukit Kiara',
  'Cheras',
  'City Centre',
  'Damansara',
  'Damansara Heights',
  'Desa Pandan',
  'Desa ParkCity',
  'Desa Petaling',
  'Dutamas',
  'Federal Hill',
  'Gombak',
  'Jalan Ipoh',
  'Jalan Klang Lama',
  'Jalan Kuching',
  'Jalan U-Thant',
  'KL City',
  'KL Eco City',
  'KL Sentral',
  'KLCC',
  'Kepong',
  'Keramat',
  'Kota Damansara',
  'Kuchai Lama',
  'Mid Valley City',
  'Mont Kiara',
  'OUG',
  'Pandan Indah',
  'Pandan Jaya',
  'Pandan Perdana',
  'Pantai',
  'Petaling Jaya',
  'Puchong',
  'Salak Selatan',
  'Segambut',
  'Sentul',
  'Seputeh',
  'Setapak',
  'Setiawangsa',
  'Sri Hartamas',
  'Sri Petaling',
  'Sungai Besi',
  'Taman Desa',
  'Taman Duta',
  'Taman Melawati',
  'Taman Tun Dr Ismail',
  'Titiwangsa',
  'Wangsa Maju'
] as const;
export const PROPERTY_TYPES = [
  'Apartment',
  'Bungalow',
  'Cluster House',
  'Condominium',
  'Flat',
  'Semi-detached House',
  'Serviced Residence',
  'Townhouse',
  '1-sty Terrace/Link House',
  '2-sty Terrace/Link House',
  '3-sty Terrace/Link House'
] as const;
export const FURNISHED_OPTIONS = ['Fully Furnished', 'Partially Furnished', 'Unfurnished'] as const;